import type { Building } from "./types"

// Approximate real coordinates across the affected cities, Venezuela.
// This is clearly-labeled SAMPLE data that illustrates the rescue picture
// before live reports arrive — every record carries isSample: true.
const now = Date.now()

type RawBuilding = Omit<Building, "city" | "isSample" | "signsOfLife" | "signsOfLifeAt"> & {
  victims: Omit<Building["victims"][number], "signsOfLife">[]
}

const LA_GUAIRA_BUILDINGS: RawBuilding[] = [
  {
    id: "edif-marina",
    name: "Residencias Marina Mar",
    address: "Av. La Playa, Playa Grande, Catia La Mar",
    lat: 10.6041,
    lng: -67.0152,
    floors: 12,
    apartments: 48,
    severity: "collapsed",
    status: "searching",
    accessNotes:
      "Escalera principal bloqueada en planta baja. Acceso posible por escalera de emergencia lado norte. Salida de emergencia este obstruida por escombros.",
    reportedBy: "Comité de vecinos Playa Grande",
    source: "WhatsApp",
    createdAt: now - 1000 * 60 * 60 * 6,
    updatedAt: now - 1000 * 60 * 30,
    victims: [
      {
        id: "v1",
        cedula: "V-14582931",
        name: "Ana Rodríguez",
        floor: 8,
        apartment: "8-B",
        status: "trapped",
        contactName: "Luis Rodríguez (hijo)",
        contactPhone: "+58 412 555 0148",
        notes: "Última llamada 03:10, reportó estar atrapada con su nieta.",
      },
      {
        id: "v2",
        cedula: "",
        name: "Sofía Rodríguez",
        floor: 8,
        apartment: "8-B",
        status: "trapped",
        contactName: "Luis Rodríguez (padre)",
        contactPhone: "+58 412 555 0148",
        notes: "Niña, 6 años. Junto a su abuela.",
      },
      {
        id: "v3",
        cedula: "V-6789145",
        name: "Carlos Mendoza",
        floor: 4,
        apartment: "4-A",
        status: "missing",
        contactName: "María Mendoza (esposa)",
        contactPhone: "+58 414 555 0192",
        notes: "Sin contacto desde el primer sismo.",
      },
    ],
  },
  {
    id: "edif-coral",
    name: "Edificio Coral",
    address: "Calle Real de Maiquetía, Maiquetía",
    lat: 10.5989,
    lng: -66.9835,
    floors: 8,
    apartments: 32,
    severity: "severe",
    status: "searching",
    accessNotes: "Fachada con grietas estructurales. Escaleras transitables hasta el piso 5.",
    reportedBy: "Bomberos voluntarios",
    source: "Telegram",
    createdAt: now - 1000 * 60 * 60 * 5,
    updatedAt: now - 1000 * 60 * 45,
    victims: [
      {
        id: "v4",
        cedula: "V-25671903",
        name: "José Pérez",
        floor: 6,
        apartment: "6-C",
        status: "missing",
        contactName: "Carmen Pérez (hermana)",
        contactPhone: "+58 416 555 0177",
        notes: "",
      },
      {
        id: "v5",
        cedula: "",
        name: "Familia Gutiérrez (3)",
        floor: 7,
        apartment: "7-A",
        status: "trapped",
        contactName: "Vecino del 7-B",
        contactPhone: "+58 412 555 0203",
        notes: "Se escuchan voces detrás de la puerta del 7-A.",
      },
    ],
  },
  {
    id: "edif-vista",
    name: "Conjunto Vista al Mar",
    address: "Av. Principal de Macuto, Macuto",
    lat: 10.6089,
    lng: -66.8871,
    floors: 6,
    apartments: 24,
    severity: "partial",
    status: "pending",
    accessNotes: "Daño en columnas del estacionamiento. Edificio en pie pero evacuado.",
    reportedBy: "Cruz Roja local",
    source: "Reporte directo",
    createdAt: now - 1000 * 60 * 60 * 4,
    updatedAt: now - 1000 * 60 * 60 * 2,
    victims: [
      {
        id: "v6",
        cedula: "V-11203455",
        name: "Pedro Salas",
        floor: 3,
        apartment: "3-D",
        status: "rescued",
        contactName: "Rosa Salas (madre)",
        contactPhone: "+58 424 555 0210",
        notes: "Rescatado con vida, trasladado a punto médico Caraballeda.",
      },
    ],
  },
  {
    id: "edif-puerto",
    name: "Residencias Puerto Viejo",
    address: "Sector El Cojo, La Guaira",
    lat: 10.6018,
    lng: -66.9331,
    floors: 10,
    apartments: 40,
    severity: "collapsed",
    status: "pending",
    accessNotes: "Colapso parcial de losas superiores. Acceso peligroso, requiere apuntalamiento.",
    reportedBy: "Familiares en sitio",
    source: "Instagram",
    createdAt: now - 1000 * 60 * 60 * 3,
    updatedAt: now - 1000 * 60 * 60,
    victims: [
      {
        id: "v7",
        cedula: "V-30558712",
        name: "Daniela Ríos",
        floor: 9,
        apartment: "9-A",
        status: "missing",
        contactName: "Andrés Ríos (esposo)",
        contactPhone: "+58 412 555 0233",
        notes: "Trabajaba desde casa al momento del sismo.",
      },
      {
        id: "v8",
        cedula: "V-3912487",
        name: "Sr. Hernández",
        floor: 2,
        apartment: "2-B",
        status: "missing",
        contactName: "Sobrino",
        contactPhone: "+58 414 555 0241",
        notes: "Adulto mayor, movilidad reducida.",
      },
    ],
  },
  {
    id: "edif-palmar",
    name: "Edificio El Palmar",
    address: "Av. Soublette, Caraballeda",
    lat: 10.6125,
    lng: -66.8503,
    floors: 5,
    apartments: 20,
    severity: "partial",
    status: "cleared",
    accessNotes: "Inspeccionado por equipo estructural. Todos los residentes localizados.",
    reportedBy: "Equipo internacional (Chile)",
    source: "Reporte directo",
    createdAt: now - 1000 * 60 * 60 * 7,
    updatedAt: now - 1000 * 60 * 90,
    victims: [],
  },
  {
    id: "edif-faro",
    name: "Torre Faro",
    address: "Urb. Pariata, Maiquetía",
    lat: 10.5953,
    lng: -66.9912,
    floors: 14,
    apartments: 56,
    severity: "severe",
    status: "searching",
    accessNotes: "Inclinación visible de la estructura. Solo acceso por planta baja autorizado.",
    reportedBy: "Protección Civil",
    source: "Twitter/X",
    createdAt: now - 1000 * 60 * 60 * 2,
    updatedAt: now - 1000 * 60 * 20,
    victims: [
      {
        id: "v9",
        cedula: "V-27890341",
        name: "Valentina Castro",
        floor: 11,
        apartment: "11-C",
        status: "trapped",
        contactName: "Madre",
        contactPhone: "+58 416 555 0259",
        notes: "Mensaje de voz por WhatsApp a las 04:02.",
      },
      {
        id: "v10",
        cedula: "V-18456220",
        name: "Miguel Ángel Torres",
        floor: 1,
        apartment: "PB-2",
        status: "missing",
        contactName: "Compañero de trabajo",
        contactPhone: "+58 424 555 0266",
        notes: "",
      },
    ],
  },
]

// Caracas — coordinates across Petare, Catia, El Valle and Chacao parishes.
const CARACAS_BUILDINGS: RawBuilding[] = [
  {
    id: "ccs-petare",
    name: "Bloque 7, Barrio José Félix Ribas",
    address: "Petare, Sucre, Caracas",
    lat: 10.4889,
    lng: -66.8167,
    floors: 6,
    apartments: 30,
    severity: "collapsed",
    status: "searching",
    accessNotes:
      "Acceso vehicular imposible por callejones estrechos. Solo a pie. Estructura inestable, riesgo de derrumbe secundario.",
    reportedBy: "Brigada comunitaria Petare",
    source: "WhatsApp",
    createdAt: now - 1000 * 60 * 60 * 5,
    updatedAt: now - 1000 * 60 * 25,
    victims: [
      {
        id: "v11",
        cedula: "V-5238901",
        name: "Yolanda Bastidas",
        floor: 5,
        apartment: "5-2",
        status: "trapped",
        contactName: "Hija (Génesis)",
        contactPhone: "+58 414 555 0301",
        notes: "Se escuchan golpes desde el apartamento.",
      },
      {
        id: "v12",
        cedula: "",
        name: "Familia Colmenares (4)",
        floor: 3,
        apartment: "3-1",
        status: "missing",
        contactName: "Vecina",
        contactPhone: "+58 412 555 0318",
        notes: "Dos adultos, dos niños.",
      },
    ],
  },
  {
    id: "ccs-catia",
    name: "Residencias Sucre",
    address: "Av. Sucre, Catia, Libertador, Caracas",
    lat: 10.5114,
    lng: -66.9289,
    floors: 11,
    apartments: 44,
    severity: "severe",
    status: "searching",
    accessNotes: "Grietas en columnas de planta baja. Ascensores fuera de servicio. Escalera norte transitable.",
    reportedBy: "Bomberos del Distrito Capital",
    source: "Reporte directo",
    createdAt: now - 1000 * 60 * 60 * 4,
    updatedAt: now - 1000 * 60 * 50,
    victims: [
      {
        id: "v13",
        cedula: "V-4019256",
        name: "Régulo Antonio Páez",
        floor: 9,
        apartment: "9-D",
        status: "missing",
        contactName: "Hijo",
        contactPhone: "+58 424 555 0327",
        notes: "Adulto mayor, usa bastón.",
      },
    ],
  },
  {
    id: "ccs-elvalle",
    name: "Unidad Residencial El Valle",
    address: "Av. Intercomunal, El Valle, Caracas",
    lat: 10.4583,
    lng: -66.9,
    floors: 15,
    apartments: 60,
    severity: "partial",
    status: "pending",
    accessNotes: "Daño en fachada y vidrios. Edificio evacuado preventivamente, pendiente inspección estructural.",
    reportedBy: "Junta de condominio",
    source: "Telegram",
    createdAt: now - 1000 * 60 * 60 * 3,
    updatedAt: now - 1000 * 60 * 60 * 2,
    victims: [],
  },
  {
    id: "ccs-chacao",
    name: "Edificio Chacao Centro",
    address: "Av. Francisco de Miranda, Chacao, Caracas",
    lat: 10.4978,
    lng: -66.8536,
    floors: 9,
    apartments: 27,
    severity: "stable",
    status: "cleared",
    accessNotes: "Inspeccionado por ingenieros del municipio. Sin daño estructural. Residentes pueden regresar.",
    reportedBy: "Protección Civil Chacao",
    source: "Reporte directo",
    createdAt: now - 1000 * 60 * 60 * 6,
    updatedAt: now - 1000 * 60 * 80,
    victims: [],
  },
]

// Los Teques — Miranda, southwest of Caracas.
const LOS_TEQUES_BUILDINGS: RawBuilding[] = [
  {
    id: "lt-centro",
    name: "Residencias El Tambor",
    address: "Sector El Tambor, Los Teques, Miranda",
    lat: 10.3447,
    lng: -67.0436,
    floors: 7,
    apartments: 28,
    severity: "severe",
    status: "searching",
    accessNotes: "Escombros en entrada principal. Acceso por estacionamiento posterior.",
    reportedBy: "Protección Civil Miranda",
    source: "WhatsApp",
    createdAt: now - 1000 * 60 * 60 * 4,
    updatedAt: now - 1000 * 60 * 35,
    victims: [
      {
        id: "v14",
        cedula: "V-22784510",
        name: "Carolina Méndez",
        floor: 6,
        apartment: "6-A",
        status: "trapped",
        contactName: "Esposo",
        contactPhone: "+58 416 555 0344",
        notes: "Contacto telefónico intermitente.",
      },
    ],
  },
  {
    id: "lt-vista",
    name: "Conjunto Lomas de Urquía",
    address: "Carretera Panamericana, Los Teques, Miranda",
    lat: 10.3669,
    lng: -67.0561,
    floors: 5,
    apartments: 18,
    severity: "partial",
    status: "pending",
    accessNotes: "Daño moderado en muros divisorios. Estructura principal en pie.",
    reportedBy: "Vecinos del conjunto",
    source: "Instagram",
    createdAt: now - 1000 * 60 * 60 * 3,
    updatedAt: now - 1000 * 60 * 95,
    victims: [
      {
        id: "v15",
        cedula: "V-7653108",
        name: "Sr. Aular",
        floor: 2,
        apartment: "2-C",
        status: "missing",
        contactName: "Nuera",
        contactPhone: "+58 412 555 0351",
        notes: "",
      },
    ],
  },
]

function withCity(list: RawBuilding[], city: string): Building[] {
  return list.map((b) => ({
    ...b,
    city,
    isSample: true,
    signsOfLife: false,
    signsOfLifeAt: null,
    victims: b.victims.map((v) => ({ ...v, signsOfLife: null })),
  }))
}

// All sample buildings, tagged with their city and clearly marked as samples.
export const SEED_BUILDINGS: Building[] = [
  ...withCity(LA_GUAIRA_BUILDINGS, "la-guaira"),
  ...withCity(CARACAS_BUILDINGS, "caracas"),
  ...withCity(LOS_TEQUES_BUILDINGS, "los-teques"),
]
