import type { Building } from "./types"

// Approximate real coordinates along the La Guaira / Vargas coast, Venezuela.
// This sample data illustrates the rescue picture before live reports arrive.
const now = Date.now()

export const SEED_BUILDINGS: Building[] = [
  {
    id: "edif-marina",
    name: "Residencias Marina Mar",
    address: "Av. La Playa, Playa Grande, Catia La Mar",
    lat: 10.6041,
    lng: -67.0152,
    floors: 12,
    apartments: 48,
    severity: "collapsed",
    status: "searching",
    accessNotes:
      "Escalera principal bloqueada en planta baja. Acceso posible por escalera de emergencia lado norte. Salida de emergencia este obstruida por escombros.",
    reportedBy: "Comité de vecinos Playa Grande",
    source: "WhatsApp",
    createdAt: now - 1000 * 60 * 60 * 6,
    updatedAt: now - 1000 * 60 * 30,
    victims: [
      {
        id: "v1",
        name: "Ana Rodríguez",
        floor: 8,
        apartment: "8-B",
        status: "trapped",
        contactName: "Luis Rodríguez (hijo)",
        contactPhone: "+58 412 555 0148",
        notes: "Última llamada 03:10, reportó estar atrapada con su nieta.",
      },
      {
        id: "v2",
        name: "Sofía Rodríguez",
        floor: 8,
        apartment: "8-B",
        status: "trapped",
        contactName: "Luis Rodríguez (padre)",
        contactPhone: "+58 412 555 0148",
        notes: "Niña, 6 años. Junto a su abuela.",
      },
      {
        id: "v3",
        name: "Carlos Mendoza",
        floor: 4,
        apartment: "4-A",
        status: "missing",
        contactName: "María Mendoza (esposa)",
        contactPhone: "+58 414 555 0192",
        notes: "Sin contacto desde el primer sismo.",
      },
    ],
  },
  {
    id: "edif-coral",
    name: "Edificio Coral",
    address: "Calle Real de Maiquetía, Maiquetía",
    lat: 10.5989,
    lng: -66.9835,
    floors: 8,
    apartments: 32,
    severity: "severe",
    status: "searching",
    accessNotes: "Fachada con grietas estructurales. Escaleras transitables hasta el piso 5.",
    reportedBy: "Bomberos voluntarios",
    source: "Telegram",
    createdAt: now - 1000 * 60 * 60 * 5,
    updatedAt: now - 1000 * 60 * 45,
    victims: [
      {
        id: "v4",
        name: "José Pérez",
        floor: 6,
        apartment: "6-C",
        status: "missing",
        contactName: "Carmen Pérez (hermana)",
        contactPhone: "+58 416 555 0177",
        notes: "",
      },
      {
        id: "v5",
        name: "Familia Gutiérrez (3)",
        floor: 7,
        apartment: "7-A",
        status: "trapped",
        contactName: "Vecino del 7-B",
        contactPhone: "+58 412 555 0203",
        notes: "Se escuchan voces detrás de la puerta del 7-A.",
      },
    ],
  },
  {
    id: "edif-vista",
    name: "Conjunto Vista al Mar",
    address: "Av. Principal de Macuto, Macuto",
    lat: 10.6089,
    lng: -66.8871,
    floors: 6,
    apartments: 24,
    severity: "partial",
    status: "pending",
    accessNotes: "Daño en columnas del estacionamiento. Edificio en pie pero evacuado.",
    reportedBy: "Cruz Roja local",
    source: "Reporte directo",
    createdAt: now - 1000 * 60 * 60 * 4,
    updatedAt: now - 1000 * 60 * 60 * 2,
    victims: [
      {
        id: "v6",
        name: "Pedro Salas",
        floor: 3,
        apartment: "3-D",
        status: "rescued",
        contactName: "Rosa Salas (madre)",
        contactPhone: "+58 424 555 0210",
        notes: "Rescatado con vida, trasladado a punto médico Caraballeda.",
      },
    ],
  },
  {
    id: "edif-puerto",
    name: "Residencias Puerto Viejo",
    address: "Sector El Cojo, La Guaira",
    lat: 10.6018,
    lng: -66.9331,
    floors: 10,
    apartments: 40,
    severity: "collapsed",
    status: "pending",
    accessNotes: "Colapso parcial de losas superiores. Acceso peligroso, requiere apuntalamiento.",
    reportedBy: "Familiares en sitio",
    source: "Instagram",
    createdAt: now - 1000 * 60 * 60 * 3,
    updatedAt: now - 1000 * 60 * 60,
    victims: [
      {
        id: "v7",
        name: "Daniela Ríos",
        floor: 9,
        apartment: "9-A",
        status: "missing",
        contactName: "Andrés Ríos (esposo)",
        contactPhone: "+58 412 555 0233",
        notes: "Trabajaba desde casa al momento del sismo.",
      },
      {
        id: "v8",
        name: "Sr. Hernández",
        floor: 2,
        apartment: "2-B",
        status: "missing",
        contactName: "Sobrino",
        contactPhone: "+58 414 555 0241",
        notes: "Adulto mayor, movilidad reducida.",
      },
    ],
  },
  {
    id: "edif-palmar",
    name: "Edificio El Palmar",
    address: "Av. Soublette, Caraballeda",
    lat: 10.6125,
    lng: -66.8503,
    floors: 5,
    apartments: 20,
    severity: "partial",
    status: "cleared",
    accessNotes: "Inspeccionado por equipo estructural. Todos los residentes localizados.",
    reportedBy: "Equipo internacional (Chile)",
    source: "Reporte directo",
    createdAt: now - 1000 * 60 * 60 * 7,
    updatedAt: now - 1000 * 60 * 90,
    victims: [],
  },
  {
    id: "edif-faro",
    name: "Torre Faro",
    address: "Urb. Pariata, Maiquetía",
    lat: 10.5953,
    lng: -66.9912,
    floors: 14,
    apartments: 56,
    severity: "severe",
    status: "searching",
    accessNotes: "Inclinación visible de la estructura. Solo acceso por planta baja autorizado.",
    reportedBy: "Protección Civil",
    source: "Twitter/X",
    createdAt: now - 1000 * 60 * 60 * 2,
    updatedAt: now - 1000 * 60 * 20,
    victims: [
      {
        id: "v9",
        name: "Valentina Castro",
        floor: 11,
        apartment: "11-C",
        status: "trapped",
        contactName: "Madre",
        contactPhone: "+58 416 555 0259",
        notes: "Mensaje de voz por WhatsApp a las 04:02.",
      },
      {
        id: "v10",
        name: "Miguel Ángel Torres",
        floor: 1,
        apartment: "PB-2",
        status: "missing",
        contactName: "Compañero de trabajo",
        contactPhone: "+58 424 555 0266",
        notes: "",
      },
    ],
  },
]
